version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    container_name: add_neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4JLABS_PLUGINS='["graph-data-science"]'
  add_engine_1:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
#      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS1
      - FORMULATION=TDRS1
      - RUN_NUMBER=1
    container_name: add_engine_1
#    tty: true
    entrypoint: ["gradle", "run"]
  add_engine_2:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
#      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS2
      - FORMULATION=TDRS2
      - RUN_NUMBER=2
    container_name: add_engine_2
    entrypoint: ["gradle", "run"]
  add_engine_3:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS3
      - FORMULATION=TDRS3
      - RUN_NUMBER=3
    container_name: add_engine_3
    entrypoint: ["gradle", "run"]
  add_engine_4:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS4
      - FORMULATION=TDRS4
      - RUN_NUMBER=4
    container_name: add_engine_4
    entrypoint: ["gradle", "run"]
  add_engine_5:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS5
      - FORMULATION=TDRS5
      - RUN_NUMBER=5
    container_name: add_engine_5
    entrypoint: ["gradle", "run"]
  add_engine_6:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS6
      - FORMULATION=TDRS6
      - RUN_NUMBER=6
    container_name: add_engine_6
    entrypoint: ["gradle", "run"]
  add_engine_7:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS7
      - FORMULATION=TDRS7
      - RUN_NUMBER=7
    container_name: add_engine_7
    entrypoint: ["gradle", "run"]
  add_engine_8:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS8
      - FORMULATION=TDRS8
      - RUN_NUMBER=8
    container_name: add_engine_8
    entrypoint: ["gradle", "run"]
  add_engine_9:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS9
      - FORMULATION=TDRS9
      - RUN_NUMBER=9
    container_name: add_engine_9
    entrypoint: [ "gradle", "run" ]
  add_engine_10:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS10
      - FORMULATION=TDRS10
      - RUN_NUMBER=10
    container_name: add_engine_10
    entrypoint: [ "gradle", "run" ]
  add_engine_11:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS11
      - FORMULATION=TDRS11
      - RUN_NUMBER=11
    container_name: add_engine_11
    entrypoint: [ "gradle", "run" ]
  add_engine_12:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS12
      - FORMULATION=TDRS12
      - RUN_NUMBER=12
    container_name: add_engine_12
    entrypoint: [ "gradle", "run" ]
  add_engine_13:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS13
      - FORMULATION=TDRS13
      - RUN_NUMBER=13
    container_name: add_engine_13
    entrypoint: [ "gradle", "run" ]
  add_engine_14:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS14
      - FORMULATION=TDRS14
      - RUN_NUMBER=14
    container_name: add_engine_14
    entrypoint: [ "gradle", "run" ]
  add_engine_15:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS15
      - FORMULATION=TDRS15
      - RUN_NUMBER=15
    container_name: add_engine_15
    entrypoint: [ "gradle", "run" ]
  add_engine_16:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS16
      - FORMULATION=TDRS16
      - RUN_NUMBER=16
    container_name: add_engine_16
    entrypoint: [ "gradle", "run" ]
  add_engine_17:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS17
      - FORMULATION=TDRS17
      - RUN_NUMBER=17
    container_name: add_engine_17
    entrypoint: [ "gradle", "run" ]
  add_engine_18:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS18
      - FORMULATION=TDRS18
      - RUN_NUMBER=18
    container_name: add_engine_18
    entrypoint: [ "gradle", "run" ]
  add_engine_19:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS19
      - FORMULATION=TDRS19
      - RUN_NUMBER=19
    container_name: add_engine_19
    entrypoint: [ "gradle", "run" ]
  add_engine_20:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS20
      - FORMULATION=TDRS20
      - RUN_NUMBER=20
    container_name: add_engine_20
    entrypoint: [ "gradle", "run" ]
  add_engine_21:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS21
      - FORMULATION=TDRS21
      - RUN_NUMBER=21
    container_name: add_engine_21
    entrypoint: [ "gradle", "run" ]
  add_engine_22:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS22
      - FORMULATION=TDRS22
      - RUN_NUMBER=22
    container_name: add_engine_22
    entrypoint: [ "gradle", "run" ]
  add_engine_23:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS23
      - FORMULATION=TDRS23
      - RUN_NUMBER=23
    container_name: add_engine_23
    entrypoint: [ "gradle", "run" ]
  add_engine_24:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS24
      - FORMULATION=TDRS24
      - RUN_NUMBER=24
    container_name: add_engine_24
    entrypoint: [ "gradle", "run" ]
  add_engine_25:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS25
      - FORMULATION=TDRS25
      - RUN_NUMBER=25
    container_name: add_engine_25
    entrypoint: [ "gradle", "run" ]
  add_engine_26:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS26
      - FORMULATION=TDRS26
      - RUN_NUMBER=26
    container_name: add_engine_26
    entrypoint: [ "gradle", "run" ]
  add_engine_27:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS27
      - FORMULATION=TDRS27
      - RUN_NUMBER=27
    container_name: add_engine_27
    entrypoint: [ "gradle", "run" ]
  add_engine_28:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS28
      - FORMULATION=TDRS28
      - RUN_NUMBER=28
    container_name: add_engine_28
    entrypoint: [ "gradle", "run" ]
  add_engine_29:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS29
      - FORMULATION=TDRS29
      - RUN_NUMBER=29
    container_name: add_engine_29
    entrypoint: [ "gradle", "run" ]
  add_engine_30:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS30
      - FORMULATION=TDRS30
      - RUN_NUMBER=30
    container_name: add_engine_30
    entrypoint: [ "gradle", "run" ]

