version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    container_name: add_neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4JLABS_PLUGINS='["graph-data-science"]'
  add_engine_1:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
#      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS1
      - FORMULATION=TDRS1
      - RUN_NUMBER=1
    container_name: add_engine_1
#    tty: true
    entrypoint: ["gradle", "run"]
  add_engine_2:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
#      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS2
      - FORMULATION=TDRS2
      - RUN_NUMBER=2
    container_name: add_engine_2
    entrypoint: ["gradle", "run"]
  add_engine_3:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS3
      - FORMULATION=TDRS3
      - RUN_NUMBER=3
    container_name: add_engine_3
    entrypoint: ["gradle", "run"]
  add_engine_4:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS4
      - FORMULATION=TDRS4
      - RUN_NUMBER=4
    container_name: add_engine_4
    entrypoint: ["gradle", "run"]
  add_engine_5:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS5
      - FORMULATION=TDRS5
      - RUN_NUMBER=5
    container_name: add_engine_5
    entrypoint: ["gradle", "run"]
  add_engine_6:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS6
      - FORMULATION=TDRS6
      - RUN_NUMBER=6
    container_name: add_engine_6
    entrypoint: ["gradle", "run"]
  add_engine_7:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS7
      - FORMULATION=TDRS7
      - RUN_NUMBER=7
    container_name: add_engine_7
    entrypoint: ["gradle", "run"]
  add_engine_8:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS8
      - FORMULATION=TDRS8
      - RUN_NUMBER=8
    container_name: add_engine_8
    entrypoint: ["gradle", "run"]
  add_engine_9:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS9
      - FORMULATION=TDRS9
      - RUN_NUMBER=9
    container_name: add_engine_9
    entrypoint: [ "gradle", "run" ]
  add_engine_10:
    build: .
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      #      - /c/Users/apaza/repos/gabe/itaca/.:/itaca
      - /home/ec2-user/repos/itaca/.:/itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS10
      - FORMULATION=TDRS10
      - RUN_NUMBER=10
    container_name: add_engine_10
    entrypoint: [ "gradle", "run" ]

