version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    container_name: add_neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4JLABS_PLUGINS='["graph-data-science"]'
  add_engine_1:
    build: .
    image: add_server:alpha
    volumes:
      - type: bind
        source: ./app
        target: /decisions/app
      - type: bind
        source: ./jars
        target: /decisions/jars
      - type: bind
        source: ./debug
        target: /decisions/debug
      - type: bind
        source: ./formulations
        target: /decisions/formulations
      - type: bind
        source: ./results
        target: /decisions/results
      - type: bind
        source: /c/Users/apaza/repos/gabe/itaca/.
        target: /itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS1
      - FORMULATION=TDRS1
      - RUN_NUMBER=1
    container_name: add_engine_1
#    tty: true
    entrypoint: ["gradle", "run"]
  add_engine_2:
    build: .
    image: add_server:alpha
    volumes:
      - type: bind
        source: ./app
        target: /decisions/app
      - type: bind
        source: ./jars
        target: /decisions/jars
      - type: bind
        source: ./debug
        target: /decisions/debug
      - type: bind
        source: ./formulations
        target: /decisions/formulations
      - type: bind
        source: ./results
        target: /decisions/results
      - type: bind
        source: /c/Users/apaza/repos/gabe/itaca/.
        target: /itaca
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS2
      - FORMULATION=TDRS2
      - RUN_NUMBER=2
    container_name: add_engine_2
    entrypoint: ["gradle", "run"]