version: '3.7'
services:
  neo4j:
    image: neo4j:4.4
    container_name: add_neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4JLABS_PLUGINS='["graph-data-science"]'
  add_engine_1:
    build:
      context: .
      dockerfile: DockerfileRunGroup
    image: add_server:alpha
    volumes:
      - ./app:/decisions/app
      - ./jars:/decisions/jars
      - ./debug:/decisions/debug
      - ./formulations:/decisions/formulations
      - ./results:/decisions/results
      - /c/Users/apaza/repos/seakers/scan-engine/.:/scan
    #      - /home/ec2-user/repos/scan/.:/scan
    depends_on:
      - neo4j
    env_file: grouprun.env
    environment:
      - PROBLEM=TDRS1
      - FORMULATION=TDRS1
      - RUN_NUMBER=1
    container_name: add_engine_1
    tty: true
