version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    container_name: add_neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4JLABS_PLUGINS='["graph-data-science"]'
  add_engine_1:
    build: .
    image: add_server:alpha
    volumes:
      - type: bind
        source: .
        target: /decisions
      - type: bind
        source: /c/Users/apaza/repos/gabe/itaca/.
        target: /itaca
    env_file: grouprun.env
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - PROBLEM=TDRS_1
      - FORMULATION=TDRS_1
      - RUN_NUMBER=1
    container_name: add_engine_1
    tty: true
#    entrypoint: ["gradle", "run"]
#  add_engine_2:
#    build: .
#    image: add_server:alpha
#    volumes:
#      - type: bind
#        source: .
#        target: /decisions
#      - type: bind
#        source: /c/Users/apaza/repos/gabe/itaca/.
#        target: /itaca
#    env_file: grouprun.env
#    environment:
#      - NEO4J_URI=neo4j://neo4j:7687
#      - NEO4J_USER=neo4j
#      - NEO4J_PASSWORD=test
#      - PROBLEM=TDRS_2
#      - FORMULATION=TDRS_2
#    container_name: add_engine_2
#    entrypoint: ["gradle", "run"]